### log_level: trace debug info warn error
### default: info
log_level = "info"

### listen_address: <ip_address>:<tcp_port> that this service will listen on.
### Default: 0.0.0.0:8080
listen_address = "${LISTEN_ADDRESS:0.0.0.0:8080}"

### statistics_interval: # of seconds between statistics logging
### Default: 60 second
statistics_interval = "${STATISTICS_INTERVAL:10}"

[cache]
### capacity_count: Approx how many items to cache in memory
### Default: ~1,000 cached DID Documents
capacity_count = "${CACHE_CAPACITY_COUNT:1000}"

### expire: Cache Time To Live (TTL) for a cached entry in seconds
### Default: 300 (5 minutes)
expire = "${EXPIRE:300}"
