name: coverage

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: coverage
        run: cargo tarpaulin --engine llvm --follow-exec --post-test-delay 10
