name: coverage

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Generate code coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --engine llvm --follow-exec --post-test-delay 10 --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true