name: coverage

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      
jobs:
  rust-pipeline:
    uses: affinidi/pipeline-rust/.github/workflows/coverage.yaml@feat/code-coverage
    secrets: inherit
    with:
      coverage: 14
