name: on-push

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  rust-workflow:
    uses: affinidi/pipeline-rust/.github/workflows/on-push.yaml@main
    secrets: inherit
    with:
      auditIgnore: "RUSTSEC-2022-0040,RUSTSEC-2023-0071"
      publish_dry_run: false